#include "configs.h"
const atrac_encoding_configuration supported_encoding_configurations[] = {
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 52,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0x98,
        .codec_info = 0x2026,
        .encode_algorithm = 0,
        .needs_duplicated_samples = true,
    },
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 66,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0xc0,
        .codec_info = 0x2030,
        .encode_algorithm = 1,
        .needs_duplicated_samples = true,
    },
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 66,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0xc0,
        .codec_info = 0x22018,
        .encode_algorithm = 0,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 105,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0x130,
        .codec_info = 0x2026,
        .encode_algorithm = 0,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 132,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0x180,
        .codec_info = 0x2030,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 32,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0xc0,
        .codec_info = 0x1002417,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 48,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x118,
        .codec_info = 0x1002422,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 64,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x178,
        .codec_info = 0x100242e,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 96,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x230,
        .codec_info = 0x1002445,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 128,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x2e8,
        .codec_info = 0x100245c,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 48,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x118,
        .codec_info = 0x1002822,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 64,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x178,
        .codec_info = 0x100282e,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 96,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x230,
        .codec_info = 0x1002845,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 128,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x2e8,
        .codec_info = 0x100285c,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 160,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x3a8,
        .codec_info = 0x1002874,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 192,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x460,
        .codec_info = 0x100288b,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 256,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x5d0,
        .codec_info = 0x10028b9,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 320,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x748,
        .codec_info = 0x10028e8,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 352,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x800,
        .codec_info = 0x10028ff,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
};
const atrac_encoding_configuration *definition_from_bitrate(int bitrate) {
    for(int i = 0; i<(sizeof(supported_encoding_configurations) / sizeof(supported_encoding_configurations[0])); i++) {
        const atrac_encoding_configuration *d = &supported_encoding_configurations[i];
        if(d->bitrate_kbps == bitrate && d->channel_count == 2) return d;
    }
    return NULL;
}
